UIS = 	tagCloudTestWindow.py
UIC   =	pyside-uic --from-imports 

.PHONY: all
all: $(UIS) 


tagCloudTestWindow.py: tagCloudTestWindow.ui
	$(UIC) tagCloudTestWindow.ui -o $@

	
install: all

remove:

clean:




